Document: dlang-pegged
Title: Debian dlang-pegged Manual
Author: <insert document author here>
Abstract: This manual describes what dlang-pegged is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dlang-pegged/dlang-pegged.sgml.gz

Format: postscript
Files: /usr/share/doc/dlang-pegged/dlang-pegged.ps.gz

Format: text
Files: /usr/share/doc/dlang-pegged/dlang-pegged.text.gz

Format: HTML
Index: /usr/share/doc/dlang-pegged/html/index.html
Files: /usr/share/doc/dlang-pegged/html/*.html
